// <auto-generated />
namespace WebApplication1_MVC_Cntr_city_sta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dbdatacitystactry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbdatacitystactry));
        
        string IMigrationMetadata.Id
        {
            get { return "202204160344281_dbdatacitystactry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
