// <auto-generated />
namespace WebApplication1_MVC_Country_State_City_Register3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class populatecountrystatecity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populatecountrystatecity));
        
        string IMigrationMetadata.Id
        {
            get { return "202204121748216_populatecountrystatecity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
